name: Publish NPM

run-name: Publish NPM - ${{ github.event.inputs.package }}

on:
  workflow_dispatch:
    inputs:
      package:
        required: true
        description: 'core, artifact, cache, exec, github, glob, http-client, io, tool-cache, attest'
      test:
        default: true
        type: boolean
        description: 'If tests step is enabled'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm-publish
    permissions:
      contents: write
      id-token: write
    steps:
      - name: setup repo
        uses: actions/checkout@v4

      - name: verify package exists
        run: ls packages/${{ github.event.inputs.package }}

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://npm.pkg.github.com/

      - name: Create versions
        id: versions
        uses: voplica/sem-ver-action@v1.0.4
        with:
          gitHubToken: "${{ secrets.GITHUB_TOKEN }}"

      - name: npm install
        run: npm install

      - name: TS-Node - Update Package Version
        run: npm version v${{ steps.versions.outputs.ver_semVerNoMeta }} --allow-same-version
        working-directory: ./packages/ts-node

      - name: bootstrap
        run: npm run bootstrap

      - name: build
        run: npm run build

      - name: test
        if: ${{ github.event.inputs.test }}
        run: npm run test

      - name: pack
        run: npm pack
        working-directory: packages/${{ github.event.inputs.package }}

      - name: Publishing Package
        run: npm publish --access restricted
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_OPTIONS: --max_old_space_size=4096
        working-directory: packages/${{ github.event.inputs.package }}
